### ISSUE TITLE
Rendering Company and Job Information based on a Job ID

### ISSUE THREAD

**Issue by jhan-old** [jaemin-han/Alarina_International#7]
Hello Everyone,

I attempted many times yesterday and this morning to figure out my 'job' page to render all company information and job information when I click a specific job. I was able to set up my query (psql joint table) successfully displaying both company and job information in my terminal. In addition, I was able to set up my 'get.one' fetch to in my app.jsx file and connect to my component where I am rendering from.

Endless Attempts:
1. I was able to display all companies so i modified my code so that my new data populate.
2. Inner Join two tables and fetching from my app.jsx file and modify my component
3. Consulted with my classmates but unable to resolve the issue.
4. Utilized my project 3 as a reference for this fetch call from my database.

@trevorpreston
@gittheking
@jasonseminara
@rapala61
@irwintsay

psql
<img width="1273" alt="d1" src="https://cloud.githubusercontent.com/assets/19918594/21149888/1407ca18-c12b-11e6-8c9c-794d271eed0e.png">
model
<img width="827" alt="d2" src="https://cloud.githubusercontent.com/assets/19918594/21149886/1402e962-c12b-11e6-9fca-503393046093.png">
app.jsx 
<img width="487" alt="d3" src="https://cloud.githubusercontent.com/assets/19918594/21149887/14037bde-c12b-11e6-92d5-da6729d687b9.png">

Thank you

**Comment by trevorpreston** [comment]
queued

**Comment by gittheking** [comment]
@jaemin-han this closed?

**Comment by jhan-old** [comment]
This is now closed. 

Rafa The Man, thank you.
